const cart_items=localforage.createInstance({name:"cart_items"}),formatter=new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'});document.addEventListener('DOMContentLoaded',()=>{bulmaQuickview.attach(),fetch('data.json').then(a=>a.json()).then(a=>{printItems(a),document.getElementById('zoeken').addEventListener('keyup',c=>{let b=c.target.value;if(b!==''){let c=fuzzysort.go(b,a,{threshold:-1e4,key:'Name'});printItems(c)}else printItems(a)})}),document.getElementById('winkelwagen-levermethode').addEventListener('change',()=>{printCartItems()}),document.getElementById('winkelwagen-form').addEventListener('submit',a=>{a.preventDefault();let c=new FormData(a.target),b={form:'shop',items:[]};for(let[a,d]of c.entries())b[a]=d;document.getElementById('winkelwagen-submit-holder').getElementsByTagName('input')[0].remove(),document.getElementById('winkelwagen-submit-holder').insertAdjacentHTML('beforeend','<progress class="progress is-small is-primary" max="100">15%</progress>'),[...a.target.getElementsByTagName('input')].forEach(a=>{a.setAttribute('disabled','disabled')}),[...a.target.getElementsByTagName('textarea')].forEach(a=>{a.setAttribute('disabled','disabled')}),[...a.target.getElementsByTagName('select')].forEach(a=>{a.setAttribute('disabled','disabled')}),[...document.getElementById('producten-houder').getElementsByTagName('button')].forEach(a=>{a.setAttribute('disabled','disabled')}),cart_items.iterate(a=>{b.items.push(a)}).then(()=>{fetch('https://normalecomu6lpcai-form.functions.fnc.nl-ams.scw.cloud',{method:'POST',body:JSON.stringify(b)}).then(a=>a.json()).then(a=>{a.ok?clear('Bestelling is in orde!'):console.error.log(a)})})})});function printItems(b){const a=document.getElementById('producten-houder');a.innerHTML='',b.forEach(b=>{if(b.hasOwnProperty('obj')&&(b=b.obj),b['Track stock']==='Y'&&parseFloat(b['In stock [NORMAL.eco]'])>=1&&!isNaN(parseFloat(b['Price [NORMAL.eco]']))){let c='';b['Sold by weight']==='Y'&&(c=' per kg'),a.insertAdjacentHTML('beforeend',`<tr>
        <th class="w-75">
            ${b.Name}
        </th>
        <td class="has-text-right">
            ${formatter.format(parseFloat(b['Price [NORMAL.eco]']))+c}
        </td>
        <td>
            <button class="button is-pulled-right add-to-cart" data-item="${JSON.stringify(b).replaceAll('"',"'")}" data-show="quickview" data-target="quickview-bestelling">Toevoegen</button>
        </td>
      </tr>`)}}),bulmaQuickview.attach(),printCartItems(),resetCartActions()}function printCartItems(){const a=document.getElementById('winkelwagen-producten-houder');a.innerHTML='',cart_total=0,printCartTotal(cart_total),cart_items.iterate(b=>{cart_total=cart_total+b.count*parseFloat(b['Price [NORMAL.eco]']),printCartTotal(cart_total);let c='';b['Sold by weight']==='Y'&&(c='per kg'),a.insertAdjacentHTML('beforeend',`<tr>
      <th>
        ${b.Name}
      </th>
      <td>
        ${formatter.format(parseFloat(b['Price [NORMAL.eco]']))} ${c}
      </td>
      <td>
        ${b.count}
      </td>
      <td>
        <button class="button is-pulled-right add-to-cart" data-item="${JSON.stringify(b).replaceAll('"',"'")}">+</button>
      </td>
      <td>
        <button class="button is-pulled-right lower-in-cart" data-item="${JSON.stringify(b).replaceAll('"',"'")}">-</button>
      </td>
    </tr>`),resetCartActions()})}function addToCart(b){const a=JSON.parse(b.target.dataset.item.replaceAll("'",'"'));cart_items.keys().then(b=>{b.includes(a.Handle)?cart_items.getItem(a.Handle).then(b=>{b['Sold by weight']==='Y'?b.count=(b.count*100+5)/100:b.count=b.count+1,cart_items.setItem(a.Handle,b).then(()=>{printCartItems()})}):(a['Sold by weight']==='Y'?a.count=.05:a.count=1,cart_items.setItem(a.Handle,a).then(()=>{printCartItems()}))})}function lowerInCart(b){const a=JSON.parse(b.target.dataset.item.replaceAll("'",'"'));cart_items.keys().then(b=>{b.includes(a.Handle)&&cart_items.getItem(a.Handle).then(b=>{b['Sold by weight']==='Y'?b.count=(b.count*100-5)/100:b.count=b.count-1,b.count<=0?cart_items.removeItem(a.Handle).then(()=>{printCartItems()}):cart_items.setItem(a.Handle,b).then(()=>{printCartItems()})})})}function resetCartActions(){[...document.getElementsByClassName('add-to-cart')].forEach(a=>{a.removeEventListener('click',addToCart),a.addEventListener('click',addToCart)}),[...document.getElementsByClassName('lower-in-cart')].forEach(a=>{a.removeEventListener('click',lowerInCart),a.addEventListener('click',lowerInCart)})}function printCartTotal(a){a<=0?document.getElementById('winkelwagen-sturen').setAttribute('disabled','disabled'):document.getElementById('winkelwagen-sturen').removeAttribute('disabled');let b=document.getElementById('winkelwagen-levermethode').value.trim();b==='thuislevering'?(a=a+3,document.getElementById('winkelwagen-adres-field').classList.remove('is-hidden')):document.getElementById('winkelwagen-adres-field').classList.add('is-hidden'),document.getElementById('winkelwagen-totaal').innerText=formatter.format(a)}function clear(a=''){cart_items.clear().then(()=>{let b=document.getElementById('winkelwagen-form');[...b.getElementsByTagName('input')].forEach(a=>{a.removeAttribute('disabled')}),[...b.getElementsByTagName('textarea')].forEach(a=>{a.removeAttribute('disabled')}),[...b.getElementsByTagName('select')].forEach(a=>{a.removeAttribute('disabled')}),[...document.getElementById('producten-houder').getElementsByTagName('button')].forEach(a=>{a.removeAttribute('disabled')}),b.reset(),document.getElementById('winkelwagen-submit-holder').getElementsByTagName('progress')[0].remove(),document.getElementById('winkelwagen-submit-holder').insertAdjacentHTML('beforeend','<input type="submit" class="button" disabled id="winkelwagen-sturen" form="winkelwagen-form" value="Doorsturen">'),printCartItems(),alert(a)})}